In [5]:
import numpy as np
v=np.array([[1,2,3,1],[4,5,6,2],[7,8,9,3],[3,3,3,4]])
print("array before swap")
print(v)
v[[0,3],:]=v[[3,0],:]
print("array after swap")
print(v)

array before swap
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]
 [3 3 3 4]]
array after swap
[[3 3 3 4]
 [4 5 6 2]
 [7 8 9 3]
 [1 2 3 1]]
