In [35]:
import numpy as np
row=int(input("enter the no.of rows:"))
col=int(input("enter the no.of columns:"))
matrix1=[]
print("enter the elements of the first matrix:")
element=list(map(int,input().split()))
matrix1=np.array(element).reshape(row,col)
print(matrix1)
row=int(input("enter the no.of rows:"))
col=int(input("enter the no.of columns:"))
matrix2=[]
print("enter the elements of the second matrix:")
element=list(map(int,input().split()))
matrix2=np.array(element).reshape(row,col)
print(matrix2)

enter the no.of rows: 2
enter the no.of columns: 2


enter the elements of the first matrix:


 1 2 3 4


[[1 2]
 [3 4]]


enter the no.of rows: 2
enter the no.of columns: 2


enter the elements of the second matrix:


 4 3 2 1


[[4 3]
 [2 1]]


In [36]:
print(np.dot(matrix1,matrix2))

[[ 8  5]
 [20 13]]


In [37]:
print(np.transpose(matrix1))
print(np.transpose(matrix2))

[[1 3]
 [2 4]]
[[4 2]
 [3 1]]


In [38]:
print(np.trace(matrix1))
print(np.trace(matrix2))

5
5


In [25]:
print(np.linalg.matrix_rank(matrix1))
print(np.linalg.matrix_rank(matrix2))

2
2


In [39]:
print(np.linalg.det(matrix1))
print(np.linalg.det(matrix2))

-2.0000000000000004
-2.0


In [40]:
print(np.linalg.inv(matrix1))
print(np.linalg.inv(matrix2))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.5  1.5]
 [ 1.  -2. ]]


In [42]:
print(np.linalg.eig(matrix1))
print(np.linalg.eig(matrix2))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
EigResult(eigenvalues=array([ 5.37228132, -0.37228132]), eigenvectors=array([[ 0.90937671, -0.56576746],
       [ 0.41597356,  0.82456484]]))
